[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#4b1fcf"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#6B4FC8"
textColor = "#ffffff"
font = "sans serif"

[client]
toolbarMode = "minimal"
